export const array = [
  {
    id: '1',
    title: 'Junior Web Developer / Graduate',
    company: 'Brainnest Frontend Development Industry Training',
    date: '09/2022 - 10/2022',
    skill1: 'HTML, CSS, JavaScript',
    skill2: 'Projects available on GitHub',
    skill3: 'https://github.com/Aido12',
  },
  {
    id: '2',
    title: 'Junior Web Developer',
    company: 'AIoT Hub',
    date: '02/2022 - 07/2022',
    skill1: 'HTML, CSS',
    skill2: 'JavaScript, React',
    skill3: 'Git, GitHub',
    skill4: 'MongoDB',
    skill5: 'WebFlow',
  },
  {
    id: '3',
    title: 'Junior Web Developer / Graduate',
    company: 'UpLeveled Fullstack Web Development Bootcamp',
    date: '08/2021 - 12/2022',
    skill1: 'HTML, CSS, JavaScript',
    skill2: 'React, Next.js, TypeScript',
    skill3: 'PostgreSQL, Node.js',
    skill4: 'Training in DevOps, Softskills',
    skill5: 'Projects available on GitHub',
    skill6: 'https://github.com/Aido12/fnal‑project',
  },
  {
    id: '4',
    title: 'Duty/Shift Manager',
    company: 'Flanagans Irish Pub',
    date: '07/2014 - 04/2020',
    skill1: 'Organising and delegation',
    skill2: 'Training staff',
    skill3: 'Customer service',
    skill4: 'Stock control',
    skill5: 'Cash reports',
  },
  {
    id: '5',
    title: 'Duty/Shift Manager',
    company: '1516 Brewing Company',
    date: '07/2014 - 04/2020',
    skill1: 'Organising and delegation',
    skill2: 'Training staff',
    skill3: 'Customer service',
    skill4: 'Stock control',
    skill5: 'Cash reports',
  },
];
